"""add user cloumn

Revision ID: 7c517b24dd4f
Revises: e713023e27ce
Create Date: 2024-03-05 12:34:00.693009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c517b24dd4f'
down_revision: Union[str, None] = 'e713023e27ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tag_BK')
    op.drop_table('RECORD_BK')
    op.drop_table('PracticeTag_BK')
    op.drop_table('PracticeDetail_BK')
    op.add_column('records', sa.Column('userId', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'userId')
    op.create_table('PracticeDetail_BK',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recordId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('PracticeTag_BK',
    sa.Column('practiceDetailId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tagId', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('RECORD_BK',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('startTime', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('startMinute', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endTime', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endMinute', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('Tag_BK',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
