services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - ./.env
    container_name: practice-record-api
    image: practice-record-api
    tty: true
    stdin_open: true
    command: ["./wait-for-it.sh", "${DB_HOST}", "5432", "--", "uvicorn", "practice_record_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: practice-record-api-web
    image: practice-record-api-web
    ports:
      - "80:80"
    depends_on:
      - api